import Navbar from "@/components/Navbar/Navbar";
import { NextAuthProvider } from "./providers";
import { ChatContextProvider } from "./context/chat";
import "./index.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChatContextProvider>
          <NextAuthProvider>
            <Navbar />
            {children}
          </NextAuthProvider>
        </ChatContextProvider>
      </body>
    </html>
  );
}
